### ISSUE TITLE
'single file data'

### ISSUE THREAD

**Issue by lindemann09** [expyriment/DIF#10]
What if the data consist of        (a) a single file or        (b) a folder containing a single file?

Currently the DIF is a checksum of a single checksum. Is that redundant? Note> this does take into account the filename. Or should we define that the DIF of a single file simply as the checksum of the single file (plus prefix)? That would be very handy from many use-cases and many already existing published data.. 

Do we treat (a) and (b) differently? The python implementation can currently only handle (b).

**Comment by fladd** [comment]
I would strongly prefer to have a single procedure for all cases. That is, independent of how many files are in the directory.

I would also make having a parent directory for your data mandatory.
