### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by lindemann09** [expyriment/DIF#15]
Since we have recently updated the proposal of the DIF procedures and since we probably do some updates in the future, we should add version numbers (or dates) to the proposal. The version number of a software implementation does not necessarily specify which version of DIF it uses.  I therefore suggest version number "v1.0", before we submit the paper.

**Comment by fladd** [comment]
As discussed in chat, the versioning would be about the proposal, not the DIF itself. We will date the proposal to make clear when/if it has changed. Once a final proposal has been agreed on, it becomes the final standard.

**Comment by lindemann09** [comment]
d52eab4025b834a00247e85faa2a62a3a4449983
