### ISSUE TITLE
"C" locale sorting

### ISSUE THREAD

**Issue by lindemann09** [expyriment/DIF#2]
Shall we want to sort like Python with capital letters first?

Note: Python sorts is byte wise. But Linux sort depends on the locale!! (see "man sort" and https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do)

If we want to sort byte-wise, which I propose, we have to ensure in the batch script that sets the locale is set to "C". Accordingly, I have adapted the batch script, the one-line and, also, the R script.

see b6e437ebc987abcecd96244908f54801cbce9101

This issue is independent from the UTF-8 coding.

**Comment by fladd** [comment]
I stick to my original suggestion which is to sort according to unicode point order. This is what Python does by default (at least >3.3).

A fully compatible Bash script indeed would need to ensure that this sort order is used. If setting the locale to `C` is sufficient to achieve this I do not know.

I would *not* use any form of semantic sorting for our purpose.

**Comment by lindemann09** [comment]
That is what I say. However, the issue is that unicode point order *depends* on the locale. Therefore we have to ensure that locale is set to "C".

**Comment by fladd** [comment]
It is the other way around actually: whether unicode point order is used for sorting depends on the locale. Unicode points themselves are a standard and always have the same order (https://en.wikipedia.org/wiki/Unicode#Code_point_planes_and_blocks). That is why I would use this order.

**Comment by fladd** [comment]
I actually think `LC_ALL="en_US.UTF-8"` also sorts correctly. @lindemann09 could you confirm this? This seems to be the default locale on most Unix-like systems.

**Comment by fladd** [comment]
```
floriankrause:~/Downloads/test/你好$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
floriankrause:~/Downloads/test/你好$ ls | sort
A2.txt
a1.txt
floriankrause:~/Downloads/test/你好$ 
```

**Comment by fladd** [comment]
```
floriankrause:~/Downloads/test$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
floriankrause:~/Downloads/test$ cat file
1
a
C
B
2
c
3
A
b

floriankrause:~/Downloads/test$ sort file

1
2
3
A
B
C
a
b
c
```

**Comment by fladd** [comment]
This is getting interesting. According to this website, it should be different: http://infoheap.com/linux-sort-lc_all-sorting-rules/

But it is not on my Mac:

```
floriankrause:~/Downloads/test$ echo 1 | sort --debug
Memory to be used for sorting: 4294967296
Using collate rules of en_US.UTF-8 locale
sort_method=heapsort
1
floriankrause:~/Downloads/test$ printf "a 4\na3\n" | sort
a 4
a3
```

**Comment by fladd** [comment]
Apparently it depends on the OS vendor what `en_US.UTF-8` does:

https://stackoverflow.com/questions/27395317/why-does-utf-8-text-sort-in-different-order-between-os-x-and-linux

https://stackoverflow.com/questions/19967555/postgres-collation-differences-osx-v-ubuntu

**Comment by lindemann09** [comment]
Yes, that is exactly what I wrote before.  UTF-8 locale is ensure correct sorting. See the link I posed.

That is why I use locale "C", which does ensure correct sorting.

see Debian/Ubuntu Linux :
```
➜  ~ export LC_ALL="en_US.UTF-8"
➜  ~ sort /tmp/file             
1
2
3
a
A
b
B
c
C
➜  ~ 
➜  ~ export LC_ALL="C"                     
➜  ~ sort /tmp/file   
1
2
3
A
B
C
a
b
c
```

**Comment by lindemann09** [comment]
What is your point or issue?

**Comment by fladd** [comment]
I was just surprised to see that under MacOS `LC_ALL="C" ` and `LC_ALL="en_US.UTF-8"` actually result in identical sorting, even though that should not be the case from what I understood from the link you sent (and apparently on your specific Linux they also results in different sorting).

```
➜  ~ export LC_ALL="en_US.UTF-8"
➜  ~ sort /tmp/file             
1
2
3
A
B
C
a
b
c
➜  ~ 
➜  ~ export LC_ALL="C"                     
➜  ~ sort /tmp/file   
1
2
3
A
B
C
a
b
c
```
