### ISSUE TITLE
Bash script: Ensure UTF-8 encoding

### ISSUE THREAD

**Issue by fladd** [expyriment/DIF#4]
Right now UTF-8 encoding is assumed. We need to check if this is actually the case, and if not, decode/encode accordingly.

**Comment by lindemann09** [comment]
The question is, whether that is really needed, if Python is the reference implementation. Linux is always UTF-8 encoded, right?

It is just a illustration how it could work under Linux and MAC. It is anyway restricted to sha256.

**Comment by fladd** [comment]
Most of the time, setting the locale is an option during installation. But one can of course change it afterwards as well. So no, I don't think we can just assume UTF-8.

My initial assumption is that we were aiming also for a full bash implementation. But if it is not going to be more than the one-liner in the README, then I would argue to just leave it at this one-liner, and not have an extra script for it.

**Comment by lindemann09** [comment]
That's probably the best.
