### ISSUE TITLE
Suggesting slight adaptations of the DIF format

### ISSUE THREAD

**Issue by fladd** [expyriment/DIF#9]
The DIF format is currently of the form:

`<prefix><delimiter><postfix>`

The prefix specifies the hash function used and the delimter separates it from the postfix which is the master hash of the checksums.

I would like to discuss three specifics of that format, and suggest slight adaptations.

1. **Same case in prefix and postfix**
Currently, lower and upper case are mixed in the DIF (upper in the prefix and lower in the postfix). I would suggest to not mix lower and upper case. While technically the DIF could be considered case-insensitive, I would suggest to promote using all lower case.

2. **Delimiter symbol**
Currently, we use a slash as delimiter, similar to what DOI does. I think this is actually the main weakness of the DOI, in the sense that it makes URL parsing less obvious. For instance, if we used the DIF as an URL, and it would read https://example.com/research/data/sha-256/afa21233565a[...], it is not obvious what is part of the path and what part of the DIF.
I think we should use a different symbol. Possible alternative symbols (that are URL compatible and don't have special meaning in a URL context; see also http://www.faqs.org/rfcs/rfc1738.html) are `$-_.+!*'(),`. Of those, I personally would only consider `-_.+`. The dot might be the most intuitive one due to its common usage as delimiter in filenames (hyphen, plus or underscore would also work, though). Not only would this make it obvious which part of an URL is a DIF (https://example.com/research/data/sha-256.afa21233565a[...]), it would also solve the issue with function names that have a slash in it themselves (e.g. "SHA-512/224"). This, however, brings me to my next point.

3. **Special symbols in prefix**
Almost all function names have special symbols (e.g. dashes or slashes) in their name (e.g. "SHA-256", "SHA3-256", "SHA-512/224"). I would suggest one of the following when using function names as DIF prefix:
  
    (a) get rid of special characters entirely: "sha256", "sha3256", "sha512224" (most straight forward solution that will add the least overhead to an already very long DIF, but could lead to collisions in the futuer, if there are two hash funcions names "XY-Z" and "X-ZY"; not sure how likely that will be, though)

    (b) get rid of special characters if they are between two different classes of symbols (i.e. numbers or letters), and replace them with a dash if they are between two same classes of symbols: "sha256", "sha3-256", "sha512-224" (a bit more convoluted solution leading to the same names that OpenSSL seems to use though: https://unix.stackexchange.com/a/493065)

    A reduced form of the hash function would also be in line with what is currently used as file extensions for checksum files (e.g. "*.sha256").

Below is the result of me playing around with several options:

```
SHA-256/afa21233565a[...]
sha-256/afa21233565a[...]
sha256/afa21233565a[...]
sha256-afa21233565a[...]
sha256+afa21233565a[...]
sha256_afa21233565a[...]
sha256.afa21233565a[...]

SHA-512/224/afa21233565a[...]
sha-512/224/afa21233565a[...]
sha512224/afa21233565a[...]     |   sha512-224/afa21233565a[...]
sha512224-afa21233565a[...]     |   sha512-224-afa21233565a[...]
sha512224+afa21233565a[...]     |   sha512-224+afa21233565a[...]
sha512224_afa21233565a[...]     |   sha512-224_afa21233565a[...]
sha512224.afa21233565a[...]     |   sha512-224.afa21233565a[...]

SHA3-256/afa21233565a[...]
sha3-256/afa21233565a[...]
sha3256/afa21233565a[...]       |   sha3-256/afa21233565a[...]
sha3256-afa21233565a[...]       |   sha3-256-afa21233565a[...]
sha3256+afa21233565a[...]       |   sha3-256+afa21233565a[...]
sha3256_afa21233565a[...]       |   sha3-256_afa21233565a[...]
sha3256.afa21233565a[...]       |   sha3-256.afa21233565a[...]


File extensions:

MD5         --> *.md5
SHA-1       --> *.sha1
SHA-224     --> *.sha224
SHA-256     --> *.sha256
SHA-384     --> *.sha384
SHA-512     --> *.sha512
SHA-512/224 --> *.sha512224  |   *.sha512-224
SHA3-256    --> *.sha3256    |   *.sha3-256

```

**Comment by lindemann09** [comment]
I do agree with (1) & (2). Let's use lower cases and  '.'

(3) I would (always) argue for the most simple and efficient version, which is (a).
Future collisions are not really a problem, because they are unlikely. I think developer of future standards will be also aware of this issue and will avoid naming hash function  XY-Z, if hash fucntion X-YZ already exists. DIF might changes over time anyway, because we do not know what happens in the future. The collision you are talking about, is in my view, the smallest problem that DIF will face. It is therefore not worth sacrificing parsimony for that. 

PS: Maybe Trello is a better place for discussing this issues?

**Comment by lindemann09** [comment]
BTW: https://multiformats.io aims to solve this issue with own codes. I do not like this, because it is not human readable and requires a table with the codes. Human readability is very important for DIF. 

I am not sure if future more secure algorithms are really needed. There is also no need for faster to compute functions. Thus, I might therefore possible that there is not much more development of the  hash standards for this purposes. Nobody we buy a super computer to tamper a data set.

**Comment by fladd** [comment]
I agree that there probably will not be much need for many other functions. I can see, however, that people might prefer sha3-256 for performance reasons (or even BLAKE2). I think we will hence see mainly "sha256" and "sha3256" (and maybe "blake2b512") as prefixes. The minimal version without any special characters is, while not always optimally readable (e.g. "sha512224"), okay for me.

I also don't like that Multihash relies on a table (that thing has to be maintained somewhere by someone). It might be worth though to have a look at https://multiformats.io/multihash/#q-why-not-use-sha256-digest when we argue for using human-readable in-band coding of the hash function. Just to make sure we have good arguments against the points they bring up.

One more thing I just realized, that would argue in favor of `_` as the delimiter, is that `_` is considered a word character in regular expressions (`\w`). This would underline the fact prefix, delimiter and postfix are together actually representing "one thing" (the DIF), while the `.` delimiter stresses more on the fact that there are two independent parts that are delimited. For example, in Vim `:%s/\w\+/word/g` would replace all `_` delimited DIFs with the word "word", while it would results in "word.word" for `.` delimited DIFs. Which message do we want to send here?
